language: python

python:
  - "3.7"

env:


install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
  - cd src
  - python manage.py migrate

scripts:
  - coverage run --source='apps' manage.py test
  - coverage report --skip-covered --skip-empty --precision=1 --sort=cover --fail-under=65
