language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres

scripts:
  - cd src
  - python manage.py test